#!/bin/bash

port=8081
day="d04"

echo "START SRCIPT"
echo ""
read -n1 -r -p "Press space to start..."
echo ""
echo "_________________________EX00_________________________"
echo ""
read -n1 -r -p "Press space to continue..."
clear
user="sb"
pass="beeone"
submit="OK"
num_check="EX00 - TEST 1"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation session\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php?login='$user'&passwd='$pass'&submit='$submit
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo ""
curl -v -b cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v 'http://localhost:'$port'/'$day'/ex00/index.php'
#echo 'http://localhost:'$port'/'$day'/ex01/index.php'
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="sb"
pass="beeone"
submit="O"
num_check="EX00 - TEST 2"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation session\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php?login='$user'&passwd='$pass'&submit='$submit
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo ""
curl -v -b cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v 'http://localhost:'$port'/'$day'/ex00/index.php'
#echo 'http://localhost:'$port'/'$day'/ex01/index.php'
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="sb"
pass=0
submit="OK"
num_check="EX00 - TEST 3"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation session\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php?login='$user'&passwd='$pass'&submit='$submit
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo ""
curl -v -b cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v 'http://localhost:'$port'/'$day'/ex00/index.php'
#echo 'http://localhost:'$port'/'$day'/ex01/index.php'
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user=0
pass="beeone"
submit="OK"
num_check="EX00 - TEST 4"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation session\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php?login='$user'&passwd='$pass'&submit='$submit
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo ""
curl -v -b cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v 'http://localhost:'$port'/'$day'/ex00/index.php'
#echo 'http://localhost:'$port'/'$day'/ex01/index.php'
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user=
pass="beeone"
submit="OK"
num_check="EX00 - TEST 5"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation session\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php?login='$user'&passwd='$pass'&submit='$submit
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo ""
curl -v -b cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v 'http://localhost:'$port'/'$day'/ex00/index.php'
#echo 'http://localhost:'$port'/'$day'/ex01/index.php'
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


user="sb"
pass=
submit="OK"
num_check="EX00 - TEST 6"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation session\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v -c cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php?login='$user'&passwd='$pass'&submit='$submit
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo ""
curl -v -b cook.txt 'http://localhost:'$port'/'$day'/ex00/index.php'
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
echo "_______________________________________________"
echo -e $num_check'\033[32m Connection normal\033[39m'
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
curl -v 'http://localhost:'$port'/'$day'/ex00/index.php'
#echo 'http://localhost:'$port'/'$day'/ex01/index.php'
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to start..."
clear

echo "_________________________EX01_________________________"

if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	rm $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
fi

read -n1 -r -p "Press space to continue..."
echo ""
user="toto1"
pass="titi1"
submit="OK"
num_check="EX01 - TEST 1"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user=
pass="titi1"
submit="OK"
num_check="EX01 - TEST 2"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Mauvais creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="toto1"
pass=
submit="OK"
num_check="EX01 - TEST 3"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Mauvais creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="toto1"
pass="titi1"
submit="KO"
num_check="EX01 - TEST 4"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Mauvais creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="toto1"
pass="titi1"
submit=
num_check="EX01 - TEST 5"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Mauvais creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="titi1"
pass="toto1"
submit="OK"
num_check="EX01 - TEST 6"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation new compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear



user="titi1"
pass="toto1"
submit="OK"
num_check="EX01 - TEST 7"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation de compte deja existant\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

if [ -d $HOME"/http/Piscines/htdocs/"$day"/private" ]; then
	{
	rm -rf $HOME"/http/Piscines/htdocs/"$day"/private"
	}
fi

<<COMMENT
echo "Suppression de /private/passwd"\n
echo "Creation d'un repertoire /private/passwd"
mkdir $HOME"/http/Piscines/htdocs/"$day"/private"
mkdir $HOME"/http/Piscines/htdocs/"$day"/private/passwd"

user="titi1"
pass="toto1"
submit="OK"
num_check="EX01 - TEST 7"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear
COMMENT

echo "_________________________EX02_________________________"

if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	rm $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
fi

read -n1 -r -p "Press space to continue..."
echo ""
user="x"
pass="21"
submit="OK"
num_check="EX02"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="x"
pass="42"
oldpass="21"
submit="OK"
num_check="EX02 - TEST 1"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:21"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="y"
pass="21"
oldpass="42"
submit="OK"
num_check="EX02 - TEST 2"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:42"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user=
pass="21"
oldpass="42"
submit="KO"
num_check="EX02 - TEST 3"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:42"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="x"
pass='21'
oldpass="42"
submit=
num_check="EX02 - TEST 4"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:42"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="x"
pass="42"
oldpass=
submit="OK"
num_check="EX02 - TEST 5"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:42"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


user="x"
pass=
oldpass="42"
submit="OK"
num_check="EX02 - TEST 6"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:42"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="y"
pass="-42"
submit="OK"
num_check="EX02"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation d'un deuxieme compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="y"
pass="-21"
oldpass="-42"
submit="OK"
num_check="EX02 - TEST 7"
echo -e $num_check" login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo "password actuel:-42"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Change password\033[39m login=\033[32m"$user"\033[39m&old_passwd=\033[32m"$oldpass"\033[39m&new_passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d oldpw=$oldpass -d newpw=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex02/modif.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


echo "_________________________EX03_________________________"

if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	rm $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
fi

read -n1 -r -p "Press space to continue..."
echo ""
user="toto"
pass="titi"
submit="OK"
num_check="EX03"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32m"$submit"\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit=$submit 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

user="toto"
pass="titi"
num_check="EX03 - TEST 1"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Test de connection:\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl 'http://localhost:'$port'/'$day'/ex03/login.php?login='$user'&passwd='$pass
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


user="toto"
pass="x"
num_check="EX03 - TEST 2"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Test de connection:\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl 'http://localhost:'$port'/'$day'/ex03/login.php?login='$user'&passwd='$pass
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


user="x"
pass="titi"
num_check="EX03 - TEST 3"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Test de connection:\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl 'http://localhost:'$port'/'$day'/ex03/login.php?login='$user'&passwd='$pass
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


user="x"
pass=
num_check="EX03 - TEST 4"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Test de connection:\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl 'http://localhost:'$port'/'$day'/ex03/login.php?login='$user'&passwd='$pass
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear


user=
pass="titi"
num_check="EX03 - TEST 5"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
read -n1 -r -p "Press space to continue..."
echo "" 
echo "_______________________________________________"
echo -e $num_check"\033[32m Test de connection:\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl 'http://localhost:'$port'/'$day'/ex03/login.php?login='$user'&passwd='$pass
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo -e "Display file /private/passwd\n"
if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	more $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
else
	echo -e "\033[031mProbleme: fichier passwd non existant\033[039m"
fi
echo ""
echo ""
read -n1 -r -p "Press space to continue..."
clear

if [ -f $HOME"/http/Piscines/htdocs/"$day"/private/passwd" ]; then
	rm $HOME"/http/Piscines/htdocs/"$day"/private/passwd"
fi


user="toto"
pass="titi"
num_check="EX03 - TEST 6"
echo -e $num_check" login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
rread -n1 -r -p "Press space to continue..."
echo ""
echo "_______________________________________________"
echo -e $num_check"\033[32m Creation de compte\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m&submit=\033[32mOK\033[39m"
echo -ne "\033[036m"
curl -d login=$user -d passwd=$pass -d submit="OK" 'http://localhost:'$port'/'$day'/ex01/create.php'
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
sleep 1;
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec creation cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl -c cook.txt 'http://localhost:'$port'/'$day'/ex03/login.php?login='$user'&passwd='$pass
echo -ne "\033[039m"
echo -e "\033[032mOK\033[039m"
echo ""
sleep 1;
echo "_______________________________________________"
echo -e $num_check"\033[32m Connection avec cookie\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo -ne "\033[036m"
curl -b cook.txt 'http://localhost:'$port'/'$day'/ex03/whoami.php'
echo -ne "\033[039m"
echo -e "\033[032mtoto\033[039m"
echo ""
sleep 1;
echo "_______________________________________________"
echo -e $num_check"\033[32m Logout\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
curl -b cook.txt 'http://localhost:'$port'/'$day'/ex03/logout.php'
echo ""
sleep 1;
echo "_______________________________________________"
echo -e $num_check"\033[32m whoami\033[39m login=\033[32m"$user"\033[39m&passwd=\033[32m"$pass"\033[39m"
echo ""
echo -ne "\033[036m"
curl -b cook.txt 'http://localhost:'$port'/'$day'/ex03/whoami.php'
echo -ne "\033[039m"
echo -e "\033[032mERROR\033[039m"
echo ""
echo ""
echo ""
